[config]
name = "Google Chrome Canary"
extends = "@keychord/chords-chromium/chords/com/google/Chrome/canary.toml"

[config.js]
module = '''
import createChromiumHandler from "dist/chrome.js";
export default createChromiumHandler(import.meta, "/Applications/Google Chrome Canary.app");
'''
