[config]
name = "ChatGPT Atlas"
extends = "@keychord/chords-chromium/chords/base.toml"

[config.js]
module = '''
import createChromiumHandler from "dist/chrome.js";
export default createChromiumHandler(import.meta, "/Applications/ChatGPT Atlas.app");
'''